### ISSUE TITLE
As a user, I want to be greeted by a home page so that I can access the features of the website

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#12]
### Priority: P1
- [x]  [` Landing page UI `](https://github.com/justin-cotarla/CaptionThis/issues/21)
- [x]  [` Moment React component `](https://github.com/justin-cotarla/CaptionThis/issues/23)
- [x]  [` Create GET moments endpoint `](https://github.com/justin-cotarla/CaptionThis/issues/27)
- [x]  [` Connecting to moment endpoint `](https://github.com/justin-cotarla/CaptionThis/issues/24)
- [x]  [` Refactoring Moment component `](https://github.com/justin-cotarla/CaptionThis/issues/43)

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237015-d4cea1b8-23db-11e8-976f-03190f1024fd.png)
