### ISSUE TITLE
As a user, I want to be able to create moments 

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#13]
### Priority: P1
- [x]  [` Create frontend page for moment `](https://github.com/justin-cotarla/CaptionThis/issues/19)
- [x]  [` Add upload functionality for moment creation `](https://github.com/justin-cotarla/CaptionThis/issues/20)
- [x]  [` Create PUT moments endpoint`](https://github.com/justin-cotarla/CaptionThis/issues/22)
- [x]  [`Add AWS S3 to store pictures`](https://github.com/justin-cotarla/CaptionThis/issues/54)
- [x]  [`Link frontend page to backend component`](https://github.com/justin-cotarla/CaptionThis/issues/55)

### Acceptance Test:
1. User navigates to the moment submit page (localhost/submit or 192.168.99.100/submit).
2. User fills out form and chooses an image to upload.
3. User submits the form.
4. The newly uploaded moment is displayed on the landing page.

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237020-f21ae5f6-23db-11e8-82c1-49fb1c823e75.png)
