### ISSUE TITLE
As a user, I want to receive feedback for different actions performed on the website

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#138]
### Story Points: 5

- [x]  [` Apply loading to every page on the website `](https://github.com/justin-cotarla/CaptionThis/issues/194)
- [x]  [` Add voting button changes `](https://github.com/justin-cotarla/CaptionThis/issues/195)
- [x]  [` Login Incorrect & Registration Password Incorrect `](https://github.com/justin-cotarla/CaptionThis/issues/166)

Due: Wednesday, March 7, 2018

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/38773664-6ea233d0-4020-11e8-973d-777c170f1326.png)
