### ISSUE TITLE
Add Navigation Bar on each page to redirect anywhere in the site

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#223]
### Story Points: 3

- [x]  [` Add & link new buttons `](https://github.com/justin-cotarla/CaptionThis/issues/230)
- [x]  [` Apply page header to all pages `](https://github.com/justin-cotarla/CaptionThis/issues/231)
- [x]  [` Apply logo separately to specific pages `](https://github.com/justin-cotarla/CaptionThis/issues/232)

Due: Thursday, March 15, 2018

**Comment by yasminegha** [comment]
- [x] Style & Create Custom Icons to navigation bar buttons
- [ ] Add Animation to buttons to enhance user experience

**Comment by tehblasian** [comment]
The requested changes were made.
