### ISSUE TITLE
As a user, I want the website to be usable on mobile devices 

### ISSUE THREAD

**Issue by tehblasian** [justin-cotarla/CaptionThis#381]
Story Points: 5

Tasks:
- [ ] [Make the landing page responsive](#379)
- [x] [Make the moment view page responsive](#367)
- [ ] Make the profile page responsive
- [x] [Make the create moment page responsive](#365)
