### ISSUE TITLE
Test code so that it is constantly functioning properly (backend)

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#71]
### Story Points: 13
- [x]  [` /api/auth/register `](https://github.com/justin-cotarla/CaptionThis/issues/97)
- [x]  [` /api/auth/login `](https://github.com/justin-cotarla/CaptionThis/issues/98)

- [x]  [` app/routes/moments/getMoments `](https://github.com/justin-cotarla/CaptionThis/issues/191)
- [x]  [` /app/routes/moments/putMoments`](https://github.com/justin-cotarla/CaptionThis/issues/179)

- [x]  [` /app/routes/captions/postCaptions `](https://github.com/justin-cotarla/CaptionThis/issues/139)
- [x]  [` /app/routes/captions/putCaptions `](https://github.com/justin-cotarla/CaptionThis/issues/100)
- [x] [` /app/routes/captions/getCaptions `](https://github.com/justin-cotarla/CaptionThis/issues/283)
- [x]  [` /app/routes/moments/getMoment `](https://github.com/justin-cotarla/CaptionThis/issues/182)

- [x] [` /api/auth/tokens `](https://github.com/justin-cotarla/CaptionThis/issues/177)

- [x] [` DatabaseUtil `](https://github.com/justin-cotarla/CaptionThis/issues/217)
- [x] [` AuthUtil `](https://github.com/justin-cotarla/CaptionThis/issues/218)

Due: Wednesday, March 7th, 2018
