### ISSUE TITLE
As a user, I want the landing page, login page and registration page to look good so that I will be more likely to use it

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#73]
### Story Points: 13
- [x]  [` Improve Login Page `](https://github.com/justin-cotarla/CaptionThis/issues/74)
- [x]  [` Improve Registration Page `](https://github.com/justin-cotarla/CaptionThis/issues/75)
- [x]  [` Modify the appearance of the Moments `](https://github.com/justin-cotarla/CaptionThis/issues/151)

Due: Tuesday, March 8th, 2018

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237053-705264f8-23dc-11e8-9d77-89b8722f42ee.png)
