### ISSUE TITLE
Write consistent response code format

### ISSUE THREAD

**Issue by justin-cotarla** [justin-cotarla/CaptionThis#89]
- [x] [` Create response code format `](https://github.com/justin-cotarla/CaptionThis/issues/236)
- [x] [` Refactor response codes in auth endpoints `](https://github.com/justin-cotarla/CaptionThis/issues/235)
- [x] [` Refactor response codes in moments endpoints `](https://github.com/justin-cotarla/CaptionThis/issues/237)
- [x] [` Refactor response codes in captions endpoints `](https://github.com/justin-cotarla/CaptionThis/issues/238)
- [x] [`Refactor response codes in users endpoints `](https://github.com/justin-cotarla/CaptionThis/issues/239)

Story Points: 8
Due: Wednesday, March 23, 2018
